services:
  - type: web
    name: tic-tac-toe
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: GIN_MODE
        value: release
    healthCheckPath: /